CC = g++
CFLAGS = -std=c++0x

all:
	$(CC) main.cpp $(CFLAGS) -o search_doc 
	$(CC) optionTestCluster_vector.cpp $(CFLAGS) -o optionTestCluster_vector
clean:
	\rm -f search_doc optionTestCluster_vector
